
apiVersion: v1
kind: Pod
metadata:
  name: isi-sdk-pod
  labels:
    app: isi-sdk-pod
spec:
  containers:
    - name: debug 
      image: quay.io/coulof/isi_sdk_debug:latest
      imagePullPolicy: Always
      command: ["/bin/bash", "-c", "echo Hello from OpenShift && sleep 3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
  restartPolicy: Always

